---
- name: Copy config to home directory
  become: yes
  copy:
    src: /vagrant/admin.conf
    dest: /home/ubuntu/admin.conf
    owner: ubuntu
    group: ubuntu
    mode: 0600

- name: Update Environment
  become: yes
  lineinfile:
    path: /home/ubuntu/.bashrc
    regexp: '^export KUBECONFIG='
    line: 'export KUBECONFIG=/home/ubuntu/admin.conf'
    state: present

- name: Join Kubernetes Cluster
  become: yes
  command: "kubeadm join --token 2f1a31.00f66dec74fd53f3 172.42.42.1:6443"
